import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="px-10 py-4">
        <nav className="px-4 py-2 bg-gray-300 rounded-md flex gap-2">
          <Link href="/">Home</Link>
          <Link href="/users">Users</Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
