import "./globals.css";
import Nav from "./Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="px-10 py-4">
        <Nav />
        <main>{children}</main>
      </body>
    </html>
  );
}
